### ISSUE TITLE
Xiaomi Yeelight 650 Moon support?

### ISSUE THREAD

**Issue by S474N** [Zzm317/homebridge-re-yeelight#11]
Is supported Xiaomi Yeelight 650 Moon?

Miio discover output:

> Device ID: 7xxxxxxx
> Model info: Unknown
> Address: 191.168.1.19
> Token: ???
> Support: Unknown

**Comment by malmentm** [comment]
+1

**Comment by malmentm** [comment]
@S474N Did it work?

**Comment by S474N** [comment]
Mainlight yes, but ambilight no.
