### ISSUE TITLE
Latency on connecting

### ISSUE THREAD

**Issue by semaf** [Zzm317/homebridge-re-yeelight#3]
Everytime I open Homekit, it takes around 10-15 seconds to recognize the state of the Yeelights. I cant find any reason in the logs about it.

If I do not run your script than other things are in less than a second available and states are displayed.

Running on Pi 3 and Zero W and both of them same result.

Node 8.9.3
NPM 5.6.0

**Comment by Zzm317** [comment]
check your network
re-yeelight uses miio to connect your device.
So if the device is offline or the network is not well, it will take more time to get the status of the light

**Comment by staritbusfans** [comment]
Are you using Wi-Fi connection on your Pi ? If so, try Ethernet.
