### ISSUE TITLE
miio.Device is not a constructor error

### ISSUE THREAD

**Issue by simonj82** [Zzm317/homebridge-re-yeelight#7]
Hello,
when i try to run Homebridge with homebridge-re-yeelight plugin I have this error:

/usr/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17
    this.device = new miio.Device({
                  ^

TypeError: miio.Device is not a constructor

**my config.json:**

{
    "bridge": {
        "name": "SimoBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },
    "platforms": [
        {
            "platform": "ReYeelightPlatform",
            "deviceCfgs": [{
                "type": "ColorLEDBulb",
                "ip": "Yeelight_living",
                "token": "12345678901234567890123456789012",
                "Name": "Living room light",
                "updatetimer": true,
                "interval": 5
            }]
        },
        {
            "platform": "ReYeelightPlatform",
            "deviceCfgs": [{
                "type": "ColorLEDBulb",
                "ip": "Yeelight_kitchen",
                "token": "12345678901234567890123456789012",
                "Name": "Kitchen light",
                "updatetimer": true,
                "interval": 5
            }]
        }
    ]
}

**NPM Installed Modules**

NodeJs 9.5.0 on Ubuntu 16.04.3 LTS
homebridge@0.4.37
homebridge-re-yeelight@0.0.11
miio@0.15.5

**Comment by JrCs** [comment]
See #5
